version: "3.9"  # optional since v1.27.0
services:
  chelpis-hw:
    build: .
    ports:
      - "3000:3000"

#  mysql:
#    image: mysql
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: password
#    ports:
#      - "3307:3306"